"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.GitContributionAnalyzer = void 0;
const moment_1 = __importDefault(require("moment"));
const fs = __importStar(require("fs"));
const path = __importStar(require("path"));
class GitContributionAnalyzer {
    constructor(git, config = {}) {
        this.git = git;
        this.config = {
            excludePatterns: [
                '**/*.pb.go',
                '**/*.pb.js',
                '**/*.pb.ts',
                '**/*_pb2.py',
                '**/*_pb3.py',
                '**/generated/**',
                '**/*.pb.cs',
                ...(config.excludePatterns || [])
            ]
        };
    }
    isProtobufGeneratedFile(filePath) {
        if (filePath.includes('Protos/') || filePath.includes('Protos\\')) {
            if (filePath.toLowerCase().endsWith('.cs')) {
                try {
                    const content = fs.readFileSync(filePath, 'utf8');
                    const firstFewLines = content.split('\n').slice(0, 5).join('\n');
                    return true;
                }
                catch (error) {
                    return true;
                }
            }
            return true;
        }
        if (!fs.existsSync(filePath)) {
            return false;
        }
        if (filePath.toLowerCase().endsWith('.cs')) {
            try {
                const content = fs.readFileSync(filePath, 'utf8');
                const firstFewLines = content.split('\n').slice(0, 20).join('\n');
                const markers = [
                    'Generated by the protocol buffer compiler',
                    '<auto-generated>',
                    'DO NOT EDIT',
                    'using pb = global::Google.Protobuf',
                    'using pbc = global::Google.Protobuf.Collections',
                    'namespace Google.Protobuf',
                    '#pragma warning disable'
                ];
                return markers.some(marker => firstFewLines.includes(marker));
            }
            catch (error) {
                return false;
            }
        }
        const isExcluded = this.config.excludePatterns.some(pattern => {
            const regexPattern = pattern
                .replace(/\./g, '\\.')
                .replace(/\*\*/g, '.*')
                .replace(/\*/g, '[^/]*');
            const regex = new RegExp(regexPattern);
            return regex.test(filePath);
        });
        return isExcluded;
    }
    shouldIncludeFile(file, repoPath) {
        if (file.includes('Protos/') || file.includes('Protos\\')) {
            return false;
        }
        const fullPath = path.join(repoPath, file);
        return !this.isProtobufGeneratedFile(fullPath);
    }
    getLastCommitTime() {
        return __awaiter(this, void 0, void 0, function* () {
            try {
                const rawOutput = yield this.git.raw([
                    'log',
                    '-1',
                    '--pretty=format:%aI'
                ]);
                if (rawOutput && rawOutput.trim()) {
                    const lastCommitTime = (0, moment_1.default)(rawOutput.trim());
                    if (lastCommitTime.isValid()) {
                        return lastCommitTime;
                    }
                }
            }
            catch (error) {
                console.error('Error getting last commit time:', error);
            }
            return (0, moment_1.default)();
        });
    }
    getContributionStats() {
        return __awaiter(this, arguments, void 0, function* (days = 7, startDateStr, endDateStr, authorFilter, repoPath) {
            let endDate;
            let startDate;
            if (startDateStr && endDateStr) {
                startDate = (0, moment_1.default)(startDateStr).startOf('day');
                endDate = (0, moment_1.default)(endDateStr).endOf('day');
            }
            else {
                endDate = yield this.getLastCommitTime();
                if (!endDate.isValid()) {
                    endDate = (0, moment_1.default)();
                }
                startDate = endDate.clone().subtract(days - 1, 'days').startOf('day');
                endDate = endDate.clone().endOf('day');
            }
            try {
                const rawArgs = [
                    'log',
                    '--all',
                    '--no-merges',
                    '--numstat',
                    '--date=iso-strict',
                    '--pretty=format:commit %H%n%an%n%aI%n%s%n',
                    '--since', startDate.format('YYYY-MM-DD HH:mm:ss'),
                    '--until', endDate.format('YYYY-MM-DD HH:mm:ss'),
                    '--invert-grep',
                    '--grep=^WIP',
                    '--grep=^stash',
                    '--grep=^\\[STASH\\]',
                    '--grep=^\\[stash\\]'
                ];
                if (authorFilter && authorFilter !== 'all') {
                    rawArgs.push('--author=' + authorFilter);
                }
                const rawOutput = yield this.git.raw(rawArgs);
                if (!rawOutput || !rawOutput.trim()) {
                    return {};
                }
                const stats = {};
                const commitBlocks = rawOutput.split('\ncommit ');
                for (const block of commitBlocks) {
                    if (!block.trim())
                        continue;
                    const lines = block.split('\n');
                    if (lines.length < 4)
                        continue;
                    let hash = lines[0].trim();
                    if (hash.startsWith('commit ')) {
                        hash = hash.slice(7);
                    }
                    const author = lines[1].trim();
                    const dateStr = lines[2].trim();
                    const subject = lines[3].trim();
                    if (author.toLowerCase().includes('stash') ||
                        subject.toLowerCase().includes('stash') ||
                        subject.startsWith('WIP') ||
                        subject.startsWith('[STASH]') ||
                        subject.startsWith('[stash]')) {
                        continue;
                    }
                    const date = (0, moment_1.default)(dateStr);
                    if (!date.isValid()) {
                        continue;
                    }
                    if (!stats[author]) {
                        stats[author] = {
                            author,
                            email: '',
                            startDate,
                            endDate,
                            totalCommits: 0,
                            totalInsertions: 0,
                            totalDeletions: 0,
                            totalFiles: 0,
                            dailyStats: {},
                            hourlyStats: {}
                        };
                    }
                    const dateKey = date.format('YYYY-MM-DD');
                    if (!stats[author].dailyStats[dateKey]) {
                        stats[author].dailyStats[dateKey] = {
                            commits: 0,
                            insertions: 0,
                            deletions: 0,
                            files: 0
                        };
                    }
                    const hourKey = date.format('HH');
                    if (!stats[author].hourlyStats[hourKey]) {
                        stats[author].hourlyStats[hourKey] = {
                            commits: 0,
                            insertions: 0,
                            deletions: 0,
                            files: 0
                        };
                    }
                    stats[author].totalCommits++;
                    stats[author].dailyStats[dateKey].commits++;
                    stats[author].hourlyStats[hourKey].commits++;
                    for (let i = 4; i < lines.length; i++) {
                        const line = lines[i].trim();
                        if (!line)
                            continue;
                        const [ins, del, file] = line.split('\t');
                        if (!file)
                            continue;
                        if (!this.shouldIncludeFile(file, repoPath || '')) {
                            continue;
                        }
                        const insertions = ins === '-' ? 0 : parseInt(ins) || 0;
                        const deletions = del === '-' ? 0 : parseInt(del) || 0;
                        stats[author].totalInsertions += insertions;
                        stats[author].totalDeletions += deletions;
                        stats[author].totalFiles++;
                        stats[author].dailyStats[dateKey].insertions += insertions;
                        stats[author].dailyStats[dateKey].deletions += deletions;
                        stats[author].dailyStats[dateKey].files++;
                        stats[author].hourlyStats[hourKey].insertions += insertions;
                        stats[author].hourlyStats[hourKey].deletions += deletions;
                        stats[author].hourlyStats[hourKey].files++;
                    }
                }
                for (const author in stats) {
                    stats[author].startDate = startDate;
                    stats[author].endDate = endDate;
                    const currentDate = startDate.clone();
                    while (currentDate.isSameOrBefore(endDate, 'day')) {
                        const dateKey = currentDate.format('YYYY-MM-DD');
                        if (!stats[author].dailyStats[dateKey]) {
                            stats[author].dailyStats[dateKey] = { commits: 0, insertions: 0, deletions: 0, files: 0 };
                        }
                        currentDate.add(1, 'day');
                    }
                    for (let hour = 0; hour < 24; hour++) {
                        const hk = hour.toString().padStart(2, '0');
                        if (!stats[author].hourlyStats[hk]) {
                            stats[author].hourlyStats[hk] = { commits: 0, insertions: 0, deletions: 0, files: 0 };
                        }
                    }
                }
                return stats;
            }
            catch (error) {
                console.error('Error analyzing git log:', error);
                throw error;
            }
        });
    }
}
exports.GitContributionAnalyzer = GitContributionAnalyzer;
//# sourceMappingURL=gitAnalyzer.js.map