import simpleGit, { SimpleGit } from 'simple-git';
import moment from 'moment';
import * as fs from 'fs';
import * as path from 'path';
import { Segment, useDefault } from 'segmentit';

const _segmenter = new Segment();
useDefault(_segmenter);

export interface DailyStats {
    commits: number;
    insertions: number;
    deletions: number;
    files: number;
}

export interface AuthorStats {
    author: string;
    email: string;
    startDate: moment.Moment;
    endDate: moment.Moment;
    totalCommits: number;
    totalInsertions: number;
    totalDeletions: number;
    totalFiles: number;
    dailyStats: { [date: string]: DailyStats };
    hourlyStats: { [hour: string]: DailyStats };
    weeklyHourly: number[][];
    currentStreak: number;
    longestStreak: number;
}

export interface FileChangeStats {
    file: string;
    totalCommits: number;
    totalInsertions: number;
    totalDeletions: number;
}

export interface OwnershipEntry {
    path: string;
    directory: string;
    linesByAuthor: { [author: string]: number };
    totalLines: number;
    primaryAuthor: string;
    primaryAuthorPercentage: number;
}

export interface ContributionResult {
    authorStats: { [author: string]: AuthorStats };
    fileStats: FileChangeStats[];
    ownership: OwnershipEntry[];
    wordFreq: { [word: string]: number };
    commitDetails: { [date: string]: { t: string; a: string; m: string }[] };
    heatmapDetails: { [dayHour: string]: { d: string; t: string; a: string; m: string }[] };
}

export interface GitAnalyzerConfig {
    excludePatterns: string[];
}

export class GitContributionAnalyzer {
    private git: SimpleGit;
    private config: GitAnalyzerConfig;
    constructor(git: SimpleGit, config: Partial<GitAnalyzerConfig> = {}) {
        this.git = git;
        this.config = {
            excludePatterns: [
                '**/*.pb.go',
                '**/*.pb.js',
                '**/*.pb.ts',
                '**/*_pb2.py',
                '**/*_pb3.py',
                '**/generated/**',
                '**/*.pb.cs',
                ...(config.excludePatterns || [])
            ]
        };
    }

    private isProtobufGeneratedFile(filePath: string): boolean {
        if (filePath.includes('Protos/') || filePath.includes('Protos\\')) {
            if (filePath.toLowerCase().endsWith('.cs')) {
                try {
                    const content = fs.readFileSync(filePath, 'utf8');
                    const firstFewLines = content.split('\n').slice(0, 5).join('\n');
                    return true;
                } catch (error) {
                    return true;
                }
            }
            return true;
        }

        if (!fs.existsSync(filePath)) {
            return false;
        }

        if (filePath.toLowerCase().endsWith('.cs')) {
            try {
                const content = fs.readFileSync(filePath, 'utf8');
                const firstFewLines = content.split('\n').slice(0, 20).join('\n');

                const markers = [
                    'Generated by the protocol buffer compiler',
                    '<auto-generated>',
                    'DO NOT EDIT',
                    'using pb = global::Google.Protobuf',
                    'using pbc = global::Google.Protobuf.Collections',
                    'namespace Google.Protobuf',
                    '#pragma warning disable'
                ];

                return markers.some(marker => firstFewLines.includes(marker));
            } catch (error) {
                return false;
            }
        }

        const isExcluded = this.config.excludePatterns.some(pattern => {
            const regexPattern = pattern
                .replace(/\./g, '\\.')
                .replace(/\*\*/g, '.*')
                .replace(/\*/g, '[^/]*');
            const regex = new RegExp(regexPattern);
            return regex.test(filePath);
        });

        return isExcluded;
    }

    private shouldIncludeFile(file: string, repoPath: string): boolean {
        if (file.includes('Protos/') || file.includes('Protos\\')) {
            return false;
        }

        const fullPath = path.join(repoPath, file);
        return !this.isProtobufGeneratedFile(fullPath);
    }

    private async getLastCommitTime(): Promise<moment.Moment> {
        try {
            const rawOutput = await this.git.raw([
                'log',
                '-1',
                '--pretty=format:%aI'
            ]);

            if (rawOutput && rawOutput.trim()) {
                const lastCommitTime = moment(rawOutput.trim());
                if (lastCommitTime.isValid()) {
                    return lastCommitTime;
                }
            }
        } catch (error) {
            console.error('Error getting last commit time:', error);
        }

        return moment();
    }

    async getBranches(repoPath?: string): Promise<string[]> {
        try {
            const raw = await this.git.raw(['branch', '--format=%(refname:short)']);
            return raw.trim().split('\n').filter(Boolean);
        } catch { return ['main']; }
    }

    async getContributionStats(days: number = 7, startDateStr?: string, endDateStr?: string, authorFilter?: string, repoPath?: string, branch?: string): Promise<ContributionResult> {
        let endDate: moment.Moment;
        let startDate: moment.Moment;

        if (days === 0) {
            startDate = moment(0);
            endDate = moment(0);
        } else if (startDateStr && endDateStr) {
            startDate = moment(startDateStr).startOf('day');
            endDate = moment(endDateStr).endOf('day');
        } else {
            endDate = await this.getLastCommitTime();
            if (!endDate.isValid()) {
                endDate = moment();
            }
            startDate = endDate.clone().subtract(days - 1, 'days').startOf('day');
            endDate = endDate.clone().endOf('day');
        }

        try {
            const rawArgs = [
                'log',
                branch || '--all',
                '--no-merges',
                '--numstat',
                '--date=iso-strict',
                '--pretty=format:commit %H%n%an%n%aI%n%s%n',
                '--invert-grep',
                '--grep=^WIP',
                '--grep=^stash',
                '--grep=^\\[STASH\\]',
                '--grep=^\\[stash\\]'
            ];

            if (!(days === 0 && startDateStr === undefined && endDateStr === undefined)) {
                rawArgs.push('--since', startDate.format('YYYY-MM-DD HH:mm:ss'));
                rawArgs.push('--until', endDate.format('YYYY-MM-DD HH:mm:ss'));
            }

            if (authorFilter && authorFilter !== 'all') {
                rawArgs.push('--author=' + authorFilter);
            }

            const rawOutput = await this.git.raw(rawArgs);

            if (!rawOutput || !rawOutput.trim()) {
                return { authorStats: {}, fileStats: [], ownership: [], wordFreq: {}, commitDetails: {}, heatmapDetails: {} };
            }

            const stats: { [author: string]: AuthorStats } = {};
            const allFileChanges = new Map<string, { commits: number; insertions: number; deletions: number }>();
            const allFileAuthorLines = new Map<string, Map<string, number>>();
            const allWordFreq = new Map<string, number>();
            const commitDetails: { [date: string]: { t: string; a: string; m: string }[] } = {};
            const heatmapDetails: { [dayHour: string]: { d: string; t: string; a: string; m: string }[] } = {};
            const STOP_WORDS = new Set([
                'the','a','an','and','or','but','in','on','at','to','for',
                'of','with','by','from','as','is','was','are','were','be',
                'been','being','have','has','had','do','does','did','will',
                'would','could','should','may','might','can','shall','not',
                'no','nor','so','if','then','else','when','where','why',
                'how','all','each','every','both','few','more','most',
                'other','some','such','only','own','same','than','too',
                'very','just','because','about','into','over','after',
                'before','up','out','off','down','this','that','these',
                'those','it','its','he','she','they','them','their',
                'what','which','who','whom','fix','update','add','remove',
                'change','refactor','fixed','updated','added','removed',
                'changed','refactored','wip','stash'
            ]);
            const CN_STOP = new Set([
                '的','了','是','在','我','不','人','这','那','他',
                '她','它','们','为','就','都','也','要','会','可',
                '没','有','上','中','下','前','后','大','小','多',
                '少','能','把','被','让','给','到','和','与','及',
                '或','而','则','但','然','因','所','以','对','从',
                '向','自','于','由','某','各','此','其','该','哪',
                '每','第','次','等','之','已','将','只','个','一',
                '么','还','又','再','却','只','并','去','着','过'
            ]);
            const commitBlocks = rawOutput.split('\ncommit ');

            for (const block of commitBlocks) {
                if (!block.trim()) continue;

                const lines = block.split('\n');
                if (lines.length < 4) continue;

                let hash = lines[0].trim();
                if (hash.startsWith('commit ')) {
                    hash = hash.slice(7);
                }
                const author = lines[1].trim();
                const dateStr = lines[2].trim();
                const subject = lines[3].trim();

                if (author.toLowerCase().includes('stash') ||
                    subject.toLowerCase().includes('stash') ||
                    subject.startsWith('WIP') ||
                    subject.startsWith('[STASH]') ||
                    subject.startsWith('[stash]')) {
                    continue;
                }

                const date = moment(dateStr);
                if (!date.isValid()) {
                    continue;
                }

                if (!stats[author]) {
                    stats[author] = {
                        author,
                        email: '',
                        startDate,
                        endDate,
                        totalCommits: 0,
                        totalInsertions: 0,
                        totalDeletions: 0,
                        totalFiles: 0,
                        dailyStats: {},
                        hourlyStats: {},
                        weeklyHourly: Array.from({ length: 7 }, () => new Array(24).fill(0)),
                        currentStreak: 0,
                        longestStreak: 0
                    };
                }

                const words: string[] = [];
                const segs = _segmenter.doSegment(subject);
                const CJK = /^[\u4e00-\u9fff]+$/;
                for (const s of segs) {
                    const w = s.w.trim();
                    if (w.length < 2 && !CJK.test(w)) continue;
                    const lower = w.toLowerCase();
                    if (lower.length > 2 && STOP_WORDS.has(lower)) continue;
                    if (w.length === 1 && CN_STOP.has(w)) continue;
                    words.push(w);
                }
                for (const word of words) {
                    allWordFreq.set(word, (allWordFreq.get(word) || 0) + 1);
                }

                const dayOfWeek = date.day();
                const hourNum = date.hour();
                stats[author].weeklyHourly[dayOfWeek][hourNum]++;

                const dateKey = date.format('YYYY-MM-DD');
                if (!stats[author].dailyStats[dateKey]) {
                    stats[author].dailyStats[dateKey] = {
                        commits: 0,
                        insertions: 0,
                        deletions: 0,
                        files: 0
                    };
                }

                const commitMsg = subject.length > 50 ? subject.substring(0, 50) + '…' : subject;
                const commitTime = date.format('HH:mm');
                if (!commitDetails[dateKey]) commitDetails[dateKey] = [];
                commitDetails[dateKey].push({ t: commitTime, a: author, m: commitMsg });
                const dhKey = dayOfWeek + '-' + hourNum;
                if (!heatmapDetails[dhKey]) heatmapDetails[dhKey] = [];
                heatmapDetails[dhKey].push({ d: dateKey, t: commitTime, a: author, m: commitMsg });

                const hourKey = date.format('HH');
                if (!stats[author].hourlyStats[hourKey]) {
                    stats[author].hourlyStats[hourKey] = {
                        commits: 0,
                        insertions: 0,
                        deletions: 0,
                        files: 0
                    };
                }

                stats[author].totalCommits++;
                stats[author].dailyStats[dateKey].commits++;
                stats[author].hourlyStats[hourKey].commits++;

                for (let i = 4; i < lines.length; i++) {
                    const line = lines[i].trim();
                    if (!line) continue;

                    const [ins, del, file] = line.split('\t');
                    if (!file) continue;

                    if (!this.shouldIncludeFile(file, repoPath || '')) {
                        continue;
                    }

                    const insertions = ins === '-' ? 0 : parseInt(ins) || 0;
                    const deletions = del === '-' ? 0 : parseInt(del) || 0;

                    const fe = allFileChanges.get(file) || { commits: 0, insertions: 0, deletions: 0 };
                    fe.commits++;
                    fe.insertions += insertions;
                    fe.deletions += deletions;
                    allFileChanges.set(file, fe);

                    const al = allFileAuthorLines.get(file) || new Map();
                    al.set(author, (al.get(author) || 0) + insertions + deletions);
                    allFileAuthorLines.set(file, al);

                    stats[author].totalInsertions += insertions;
                    stats[author].totalDeletions += deletions;
                    stats[author].totalFiles++;

                    stats[author].dailyStats[dateKey].insertions += insertions;
                    stats[author].dailyStats[dateKey].deletions += deletions;
                    stats[author].dailyStats[dateKey].files++;

                    stats[author].hourlyStats[hourKey].insertions += insertions;
                    stats[author].hourlyStats[hourKey].deletions += deletions;
                    stats[author].hourlyStats[hourKey].files++;
                }
            }

            if (days === 0 && startDateStr === undefined && endDateStr === undefined) {
                let minDate = moment();
                let maxDate = moment(0);
                for (const author in stats) {
                    for (const dateKey of Object.keys(stats[author].dailyStats)) {
                        const d = moment(dateKey);
                        if (d.isBefore(minDate)) minDate = d;
                        if (d.isAfter(maxDate)) maxDate = d;
                    }
                }
                if (minDate.isValid() && maxDate.isValid() && minDate.isSameOrBefore(maxDate)) {
                    startDate = minDate.startOf('day');
                    endDate = maxDate.endOf('day');
                } else {
                    startDate = moment().subtract(6, 'days').startOf('day');
                    endDate = moment().endOf('day');
                }
            }

            for (const author in stats) {
                stats[author].startDate = startDate;
                stats[author].endDate = endDate;

                const currentDate = startDate.clone();
                while (currentDate.isSameOrBefore(endDate, 'day')) {
                    const dateKey = currentDate.format('YYYY-MM-DD');
                    if (!stats[author].dailyStats[dateKey]) {
                        stats[author].dailyStats[dateKey] = { commits: 0, insertions: 0, deletions: 0, files: 0 };
                    }
                    currentDate.add(1, 'day');
                }

                for (let hour = 0; hour < 24; hour++) {
                    const hk = hour.toString().padStart(2, '0');
                    if (!stats[author].hourlyStats[hk]) {
                        stats[author].hourlyStats[hk] = { commits: 0, insertions: 0, deletions: 0, files: 0 };
                    }
                }

                if (!stats[author].weeklyHourly) {
                    stats[author].weeklyHourly = Array.from({ length: 7 }, () => new Array(24).fill(0));
                }

                const sortedDates = Object.keys(stats[author].dailyStats).sort();
                let longestRun = 0;
                let currentRun = 0;
                for (const ds of sortedDates) {
                    if (stats[author].dailyStats[ds].commits > 0) {
                        currentRun++;
                        if (currentRun > longestRun) longestRun = currentRun;
                    } else {
                        currentRun = 0;
                    }
                }
                stats[author].longestStreak = longestRun;

                let curStreak = 0;
                const cursor = endDate.clone().startOf('day');
                while (true) {
                    const key = cursor.format('YYYY-MM-DD');
                    const ds = stats[author].dailyStats[key];
                    if (ds && ds.commits > 0) {
                        curStreak++;
                        cursor.subtract(1, 'day');
                    } else {
                        break;
                    }
                }
                stats[author].currentStreak = curStreak;
            }

            const fileStats: FileChangeStats[] = Array.from(allFileChanges.entries())
                .map(([file, data]) => ({
                    file,
                    totalCommits: data.commits,
                    totalInsertions: data.insertions,
                    totalDeletions: data.deletions
                }))
                .sort((a, b) => b.totalCommits - a.totalCommits);

            const ownership: OwnershipEntry[] = Array.from(allFileAuthorLines.entries())
                .map(([file, authorLines]) => {
                    const totalLines = Array.from(authorLines.values()).reduce((s, v) => s + v, 0);
                    let primaryAuthor = '';
                    let maxLines = 0;
                    for (const [author, lines] of authorLines) {
                        if (lines > maxLines) {
                            maxLines = lines;
                            primaryAuthor = author;
                        }
                    }
                    const sep = file.includes('/') ? '/' : '\\';
                    const dir = file.includes(sep) ? file.substring(0, file.lastIndexOf(sep)) : '/';
                    return {
                        path: file,
                        directory: dir,
                        linesByAuthor: Object.fromEntries(authorLines),
                        totalLines,
                        primaryAuthor,
                        primaryAuthorPercentage: totalLines > 0 ? Math.round((maxLines / totalLines) * 100) : 0
                    };
                })
                .sort((a, b) => b.totalLines - a.totalLines);

            const wordFreqArr = Array.from(allWordFreq.entries())
                .sort((a, b) => b[1] - a[1])
                .slice(0, 100);
            const wordFreq: { [word: string]: number } = {};
            for (const [word, count] of wordFreqArr) {
                wordFreq[word] = count;
            }

            return { authorStats: stats, fileStats, ownership, wordFreq, commitDetails, heatmapDetails };
        } catch (error) {
            console.error('Error analyzing git log:', error);
            throw error;
        }
    }
}
